kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backend
  namespace: {{ .Values.name }}
  labels:
    app: backend
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ebs-csi-gp2