apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.name }}
  labels:
    name: frontend
    app: frontend
spec:  
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: frontend