apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: {{ .Values.name }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: frontend-role
  namespace: {{ .Values.name }}
subjects:
  - kind: ServiceAccount
    name: frontend
    namespace: {{ .Values.name }}
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io