apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-csi-gp2
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
